[package]
name = "xiv-otp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
google-authenticator = "0.3.0"
exitcode = "1.1.2"
reqwest = { version = "0.11.13", features = ["blocking"] }
